---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: "elastic"
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    command: "/usr/sbin/init"
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"


  - name: centos7
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    command: "/usr/sbin/init"
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  
  - name: centos8
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
    command: "/usr/sbin/init"
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro" 
  
  - name: ubuntu
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true


provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        elk_version: 7.14.0
  
verifier:
  name: ansible

scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - destroy