---
- name: add localhost to ubuntu devices
  command: 
    cmd: "echo 127.0.0.1   ubuntu >> /etc/hosts"

- name: Install Kibana apt
  apt:
    deb: "/tmp/kibana-{{ elk_version }}-amd64.deb"
    state: present
  # notify: restart kibana


