---
- name: restart kibana
  become: true
  service:
    name: kibana
    state: restarted
  when: (ansible_virtualization_type != 'docker') or (ansible_virtualization_type != 'kvm') or (ansible_connection != "community.docker.docker")
